<?php

namespace pbgroupeu\stacer_eu\Repository;

use Doctrine\ORM\Query\ResultSetMapping;
use pbgroupeu\stacer_eu\Entity\Payment;
use pbgroupeu\stacer_eu\Entity\User;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends \Doctrine\ORM\EntityRepository
{
  /**
     * Total User Payments
     *
     * @return array
   */
  public function getTotalUserPayments(User $user): array
  {
    $emn = $this->getEntityManager();

    $qbd = $emn->createQueryBuilder();
    $qbd->select('COUNT (p.id) AS totalPayments')
      ->from(Payment::class, 'p')
      ->where('p.id = :id', $user->getId());

    return $qbd->getQuery()->getResult();
  }

  /**
     * Total Payments
     *
     * @return array
   */
  public function getTotalPayments(): array
  {
    $emn = $this->getEntityManager();

    $qbd = $emn->createQueryBuilder();
    $qbd->select('COUNT (p.id) AS totalPayments')
      ->from(Payment::class, 'p');

    return $qbd->getQuery()->getResult();
  }
}
