<?php

namespace pbgroupeu\stacer_eu\Repository;

use Doctrine\ORM\Query\ResultSetMapping;
use pbgroupeu\stacer_eu\Entity\User;
use pbgroupeu\getnote_eu\Entity\SME\Payer;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
  /**
     * Total User
     *
     * @return array
   */
  public function getTotalUsers(): array
  {

    $emn = $this->getEntityManager();

    $qbd = $emn->createQueryBuilder();
    $qbd->select('COUNT (u.id) AS totalUsers')
      ->from(User::class, 'u');

    return $qbd->getQuery()->getResult();
  }

  /**
   * Membershp status retrieval
   *
   * @param  string     $email               User email
   * @return Membership        array return
   */
  public function getMembershipStatus(string $email): array
  {
    $rsm = new ResultSetMapping();
    $emn = $this->getEntityManager();

    $query = $emn->createNativeQuery('SELECT u.email, p.transaction FROM user u'
      . ' INNER JOIN payer p ON p.user = u.id'
      . ' WHERE u.email = ?', $rsm);
    $query->setParameter(1, $email);

    $membership = $query->getResult();

    return $membership;
  }
}
